apiVersion: v1
kind: ConfigMap
metadata:
  name: ai-log-analyser-config
  namespace: default
data:
  AI_SERVICE_URL: "http://ai-log-analyser-ai-service:8001"
  AWS_REGION: {{ .Values.global.awsRegion }}
  BEDROCK_MODEL_ID: {{ .Values.aiService.bedrockModelId }}
  DB_NAME: {{ .Values.database.name }}
  DB_USERNAME: {{ .Values.database.username }}
  DB_PORT: {{ .Values.database.port | quote }}