apiVersion: v1
kind: Secret
metadata:
  name: ai-log-analyser-secrets
  namespace: default
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s:%s/%s" .Values.database.username .Values.database.password .Values.database.host (.Values.database.port | toString) .Values.database.name | b64enc | quote }}