apiVersion: v1
kind: Service
metadata:
  name: ai-log-analyser-ai-service
  namespace: default
  labels:
    app: ai-service
spec:
  selector:
    app: ai-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.aiService.port }}
  type: ClusterIP